---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service-1
spec:
  selector:
    app: zookeeper-1
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
      name: client
    - protocol: TCP
      port: 2888
      targetPort: 2888
      name: follower
    - protocol: TCP
      port: 3888
      targetPort: 3888
      name: leader
---
apiVersion: v1
kind: Pod
metadata:
  name: zookeeper-1
  labels:
    app: zookeeper-1
spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:6.2.4-1-ubi8
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          env:
            - name: ZOOKEEPER_SERVERS
              value: "zookeeper-service-1:2888:3888;zookeeper-service-2:2888:3888;zookeeper-service-3:2888:3888"
            - name: ZOOKEEPER_SERVER_ID
              value: "1"
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
      nodeName: nerm-worker-7a9a3
      hostname: zookeeper-service-1
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service-2
spec:
  selector:
    app: zookeeper-2
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
      name: client
    - protocol: TCP
      port: 2888
      targetPort: 2888
      name: follower
    - protocol: TCP
      port: 3888
      targetPort: 3888
      name: leader
---
apiVersion: v1
kind: Pod
metadata:
  name: zookeeper-2
  labels:
    app: zookeeper-2
spec:
  containers:
    - name: zookeeper
      image: confluentinc/cp-zookeeper:6.2.4-1-ubi8
      ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
      env:
        - name: ZOOKEEPER_SERVERS
          value: "zookeeper-service-1:2888:3888;zookeeper-service-2:2888:3888;zookeeper-service-3:2888:3888"
        - name: ZOOKEEPER_SERVER_ID
          value: "2"
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
  nodeName: nerm-worker-7a9a7
  hostname: zookeeper-service-2
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service-3
spec:
  selector:
    app: zookeeper-3
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
      name: client
    - protocol: TCP
      port: 2888
      targetPort: 2888
      name: follower
    - protocol: TCP
      port: 3888
      targetPort: 3888
      name: leader
---
apiVersion: v1
kind: Pod
metadata:
  name: zookeeper-3
  labels:
    app: zookeeper-3
spec:
  containers:
    - name: zookeeper
      image: confluentinc/cp-zookeeper:6.2.4-1-ubi8
      ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
      env:
        - name: ZOOKEEPER_SERVERS
          value: "zookeeper-service-1:2888:3888;zookeeper-service-2:2888:3888;zookeeper-service-3:2888:3888"
        - name: ZOOKEEPER_SERVER_ID
          value: "3"
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
  nodeName: nerm-worker-7a9a8
  hostname: zookeeper-service-3