---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nerm-ca
  namespace: cert-manager
spec:
  isCA: true
  duration: 43800h # 5 years
  commonName: nerm.dev
  secretName: nerm-ca-key-pair
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
