---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: broker-cert
spec:
  isCA: false
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: broker.nerm.dev
  dnsNames:
    - broker.nerm.dev
    - www.broker.nerm.dev
  secretName: broker-key-pair
  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: password-key
        name: jks-password-secret
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  issuerRef:
    name: nerm-ca
    kind: ClusterIssuer
    group: cert-manager.io
